name: check

on:
  # Trigger the workflow when a PR has no merge conflict and either it is opened or reopened, or its
  # head branch is updated.
  # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  pull_request:

  # Trigger the workflow when the master branch is updated.
  push:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - name: Lint codebase
        run: bundle exec rubocop --parallel

  rspec:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['3.1', '3.2', '3.3', '3.4']
        include:
          - coverage_report_html: false
            coverage_report_cobertura: false
          - os: ubuntu-latest
            ruby: '3.3'
            coverage_report_html: ${{ github.ref_name == 'master' }}
            coverage_report_cobertura: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run specs
        id: rspec
        run: |
          bundle exec rspec \
            --format progress \
            --format RspecJunitFormatter \
            --out tmp/rspec_junit/${{ matrix.os }}-${{ matrix.ruby }}.xml
        env:
          # We want to customize the test suite name in JUnit reports, but we can't easily because
          # of how the 3rd-party formatter works. Hence this hack, which hopefully won't conflict
          # with the conventional use of the TEST_ENV_NUMBER variable.
          # See https://github.com/sj26/rspec_junit_formatter/blob/3f79074a9987d722976542d7d6e2ebb470ad47d1/lib/rspec_junit_formatter.rb#L19
          TEST_ENV_NUMBER: " (${{ matrix.os }}, ${{ matrix.ruby }})"
          TABULARD_COVERAGE_REPORT_HTML: ${{ matrix.coverage_report_html }}
          TABULARD_COVERAGE_REPORT_COBERTURA: ${{ matrix.coverage_report_cobertura }}

      - name: Persist the JUnit test report
        if: success() || (failure() && steps.rspec.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: rspec_junit-${{ matrix.os }}-${{ matrix.ruby }}
          path: tmp/rspec_junit/*

      - name: Persist the Cobertura coverage report
        if: matrix.coverage_report_cobertura && (success() || (failure() && steps.rspec.outcome == 'failure'))
        uses: actions/upload-artifact@v4
        with:
          name: coverage_cobertura
          path: docs/coverage/coverage.xml

      - name: Persist the HTML coverage report
        if: matrix.coverage_report_html
        uses: actions/upload-artifact@v4
        with:
          name: docs-coverage
          path: docs/coverage

  yard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - name: Generate Ruby API documentation
        run : bundle exec yard doc
      - name: Generate Ruby API documentation artifact
        if: github.ref_name == 'master'
        uses: actions/upload-artifact@v4
        with:
          name: docs-ruby
          path: docs/ruby
