name: ci

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - name: Lint codebase
        run: bundle exec rubocop --parallel

  rspec:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['3.1', '3.2', '3.3']
        include:
          - coverage_report_html: false
            coverage_report_cobertura: false
          - os: ubuntu-latest
            ruby: '3.3'
            coverage_report_html: ${{ github.ref_name == 'master' }}
            coverage_report_cobertura: true
    runs-on: ${{ matrix.os }}
    outputs:
      with_junit: ${{ steps.junit.outcome == 'success' }}
      with_simplecov_html: ${{ steps.simplecov_html.outcome == 'success' }}
      with_simplecov_cobertura: ${{ steps.simplecov_cobertura.outcome == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run specs
        id: rspec
        run: |
          bundle exec rspec \
            --format progress \
            --format RspecJunitFormatter \
            --out tmp/rspec_junit/${{ matrix.os }}-${{ matrix.ruby }}.xml
        env:
          COVERAGE_REPORT_HTML: ${{ matrix.coverage_report_html }}
          COVERAGE_REPORT_COBERTURA: ${{ matrix.coverage_report_cobertura }}
      - name: Persist JUnit reports
        id: junit
        uses: actions/upload-artifact@v4
        with:
          name: rspec_junit-${{ matrix.os }}-${{ matrix.ruby }}
          path: tmp/rspec_junit/*
      - name: Persist Cobertura reports
        id: simplecov_cobertura
        if: ${{ matrix.coverage_report_cobertura }}
        uses: actions/upload-artifact@v4
        with:
          name: simplecov_cobertura
          path: docs/coverage/coverage.xml
      - name: Persist coverage website
        id: simplecov_html
        if: ${{ matrix.coverage_report_html }}
        uses: actions/upload-artifact@v4
        with:
          name: docs-coverage
          path: docs/coverage

  report_specs:
    needs:
      - rspec
    if: (success() || failure()) && needs.rspec.outputs.with_junit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: rspec_junit-*
          path: tmp/rspec_junit
      - uses: mikepenz/action-junit-report@v4
        with:
          report_paths: tmp/rspec_junit/*
          annotate_only: true
          check_title_template: '{{TEST_NAME}}'

  report_coverage:
    needs:
      - rspec
    if: (success() || failure()) && needs.rspec.outputs.with_simplecov_cobertura
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: simplecov_cobertura
          path: tmp
      - uses: paambaati/codeclimate-action@v6
        with:
          coverageLocations: ${{github.workspace}}/tmp/coverage.xml:cobertura
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  yard:
    runs-on: ubuntu-latest
    outputs:
      with_html: ${{ steps.upload_artifact.outcome == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - name: Generate Ruby API documentation
        run : bundle exec yard doc
      - name: Generate Ruby API documentation artifact
        if: github.ref_name == 'master'
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-ruby
          path: docs/ruby

  pages:
    needs:
      - rubocop
      - rspec
      - yard
    if: needs.rspec.outputs.with_simplecov_html && needs.yard.with_html
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Fetch Ruby API documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-ruby
          path: docs/ruby
      - name: Fetch coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-coverage
          path: docs/coverage
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
