---
name: pages

on:
  workflow_run:
    workflows:
      - check
    types:
      - completed
    branches:
      - master

jobs:
  pages:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Fetch Ruby API documentation artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # required to access data from another run
          run-id: ${{ github.event.workflow_run.id }}
          name: docs-ruby
          path: docs/ruby

      - name: Fetch coverage artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # required to access data from another run
          run-id: ${{ github.event.workflow_run.id }}
          name: docs-coverage
          path: docs/coverage

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
